export const advantages = [
    [
        'free_hosting',
        'free_maintenance',
        'choose_your_techonologies',
        "one_year_warranty",
        "google_maps",
        "responsive_website",
        "progressive_web_app",
        "life_time_warranty",
    ],
    [
        'free_hosting',
        'free_maintenance',
        'choose_your_techonologies',
        "responsive_website",
        "progressive_web_app",
    ],
    [
        'free_hosting',
        'free_maintenance',
        'choose_your_techonologies',
        "one_year_warranty",
        "life_time_warranty",
    ],
    [
        "responsive_website",
    ]
]